### ISSUE TITLE
Execution cannot be interrupted with Ctrl-C

### ISSUE THREAD

**Issue by martin-ueding** [kvnkuang/pbmcapply#31]
When I do some expensive calculation and realize that I want to abort it, I can usually do that with <kbd>Ctrl</kbd><kbd>C</kbd>. With `mclapply` this also works:

```
> parallel::mclapply(1:15, function (x) Sys.sleep(1))
^C
>
```

Doing the same with `pbmclapply` nothing happens and the process gets stuck:

```
> pbmcapply::pbmclapply(1:15, function (x) Sys.sleep(1))
  |================                                            |  27%, ETA 00:03^C        

```

Note the `^C` at the end of the line.

I usually help myself by pressing <kbd>Ctrl</kbd><kbd>Z</kbd> to send the process in the background. This is what the frozen process looks like:

![screenshot_20190206_094531](https://user-images.githubusercontent.com/976924/52329835-0722f000-29f4-11e9-93a4-2cbd441cb4c7.png)

Trying to kill it with `kill 13668` with an implicit `SIGTERM` does *not* work. I have so send it a `SIGKILL` in order to get rid of it.

This is annoying because I always lose my R session in case I realize that I do not want to let that finish. In RStudio I have to restart R, but also my environment is lost.

Is there something one could do to improve `SIGINT` handling?

**Comment by kvnkuang** [comment]
Thanks for reporting this issue, Martin! Because `pbmcapply` hands over the actual parallel computation to a new process (via `future`), by killing the progress monitor (your main process), the newly created process is not affected.

I'll look into handling SIGINT signals in the main process and relay it to the parallel process. I'll post updates once I make some progress.

**Comment by qykong** [comment]
Hi Kevin,

I'd like to first thank you for `pbmcapply` package, it's really helpful! 👍 
This issue is actually the major problem I'm having when using `pbmcapply` and I'm really keen to see it fixed, so I've given it a try. I noticed `future` creates a child process and this child process creates its own descendants when calling `mclapply` as well. To kill all these processes when interrupted, I found this [blog post](https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773) provides a solution to this. Basically, we can assign a group process id to the `processMonitor` and kill it and its descendants based on the group process id on interruption. Here is what I did:
1. I noticed the `futureCall` given `plan(multiprocess)` calls `mcparallel` under the hook so I replaced it with `mcparallel`. 
2. Another reason I did this is that in order to assign the group process id I need to copy the `mcparallel` source code and insert the assignment code in between. 
3. I added the `on.exit` call to clean up processes based on the group process id.

This works on both on my macbook and ubuntu desktop so far from my tests. If you are interested in this solution, I would be more than happy to work a bit more to tidy up my code in terms of error handling and create a pull request. Keen to contribute to this 😄 

Cheers,
Quyu

**Comment by kvnkuang** [comment]
Hi Quyu,

Thank you so much for your research and fix on this issue. It looks pretty promising and I've been thinking about replacing `future` with native code as we're only using a very small portion of its functions.

It would be much appreciated if you could initiate a pull request. Once tested, I will accept it and push an update to CRAN as soon as possible.

Regards,
Kevin

**Comment by kvnkuang** [comment]
Hi Quyu,

I've merged your pull request (and a series of subsequent pushes I made) into the `dev` branch. Could you please help me test it around to make sure everything works?

Also, I updated the contribution sections to include your name (also in the `dev` branch currently). Thanks again for your contribution!

Regards,
Kevin

**Comment by qykong** [comment]
Hi Kevin,

Thanks! I just tested your dev branch on both Mac and Ubuntu regarding `pbmclapply` and `pbmcmapply` running completely and running with interruption, all worked as expected. I also tested compilation on Windows (didn't realize my code didn't compile on windows but you fixed that 😄 ). 

While testing, I noticed another trivial bug. As i'm used to `pbmclapply`, I sometimes forgot the difference in argument order between `pbmclapply`  and `pbmcmapply` where FUN is the first argument. This might cause the program hanging forever at `ReadBin`. So I guess we should handle that at the beginning of the `progressMonitor` function block with `FUN <- match.fun(FUN)`. But since this is a separate problem, we can handle it in another issue.

Regards,
Quyu

**Comment by kvnkuang** [comment]
Thanks again for your feedback! I've included the code you suggested to improve function handling.

Regards,
Kevin

**Comment by julioasotodv** [comment]
Hi!

I just encountered this same error (Ctrl-C not stopping pbcmlapply) under Linux using rscript.

Perhaps the fix by @qykong does not work anymore since the addition of `ignore.interactive`? Since I am using it from the terminal I need to switch `ignore.interactive` to `T` in order to see the progress bar, but then Ctrl-C does not work (at least in version 1.5.0)

Thank you!
